### ISSUE TITLE
这个bug localization中使用的方法和灵感是来自于哪些论文，可以分享给我吗?

### ISSUE THREAD

**Issue by cssfighting** [h4iku/bug-localization#1]

**Comment by h4iku** [comment]
Hi,
The paper is mentioned in the description of the repository:
https://www.sciencedirect.com/science/article/pii/S0306457318301092
You should read its "Related work" section for the discussion of related methods and inspirations.

By the way, I could only understand your question as much as Google Translate allowed me to.
