### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by wuyan0714** [h4iku/bug-localization#2]
Hello, I am so sorry to bother you. I know that your dataset is from "where should the bugs be fixed? More accurate information retrieval based bug localization based on bug reports". The dataset contains the “eclipse” project, but you don't seem to be using it. How do you get the source code files? I want to get the source code files of "eclipse" project, but I can't find it in his link.

**Comment by h4iku** [comment]
Hi,
You can get it from BRTracer's repository:
https://sourceforge.net/projects/brtracer/files/

**Comment by wuyan0714** [comment]
Thank you very much.
