### ISSUE TITLE
semantic similarity issue

### ISSUE THREAD

**Issue by Eng-sarah90** [h4iku/bug-localization#5]
I am very interested in your field ., 
I have this issue >how can I fix it??????

C:\Users\engsa\PycharmProjects\bug-localization\venv\Scripts\python.exe C:/Users/engsa/PycharmProjects/Deep-Loc2/buglocalizer/main.py
Parsing & Preprocessing...
Token Matching...
VSM Similarity...
Stack Trace...
Semantic Similarity...
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
C:\Users\engsa\PycharmProjects\Deep-Loc2\buglocalizer\semantic_similarity.py:30: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  simi = report_doc.similarity(src_doc)
Fixed Bug Reports...
Evaluating...
params = [0.7355616679512229, 0.34036069637522043, 0.081177960422118, 0.8318476499011435]
Top N Rank: [68, 85, 88]
Top N Rank %: [0.6938775510204082, 0.8673469387755102, 0.8979591836734694]
MRR: 0.7623212758641941
MAP: 0.6444811264908078

Process finished with exit code 0

**Comment by h4iku** [comment]
Hi, thanks for your interest.

These warnings are fine. When the vectors only have out-of-vocabulary tokens and become empty, Spacy shows these warnings to indicate this. The final result is correct.
